name: Build Emoji Release

on:
  pull_request:
    types:
      - closed

jobs:
  build-emoji-release:
    # Only run if the PR was merged and originated from the 'new-emoji-release' branch
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'new-emoji-release' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 10
          persist-credentials: false

      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
        with:
          bun-version: latest

      - name: install dependencies
        run: bun install

      - name: get new releases
        id: new-releases
        run: |
          # get the commit before the merge
          PREV_COMMIT=$(git rev-parse HEAD^)

          # retrieve emojis.lock from the previous commit
          git show $PREV_COMMIT:emojis.lock > previous_emojis.lock

          # compare versions
          BEFORE_PR=$(jq -r '.versions | keys[]' previous_emojis.lock)
          AFTER_PR=$(jq -r '.versions | keys[]' emojis.lock)

          DIFF=$(echo "$AFTER_VERSIONS" | grep -vFx "$BEFORE_VERSIONS")
          echo "DIFF_VERSIONS=$DIFF" >> $GITHUB_OUTPUT

      - name: build emoji release
        env:
          NEW_VERSIONS: ${{ steps.new-releases.outputs.DIFF }}
        run: bun run build:emoji $NEW_VERSIONS
