name: build emoji release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: Run the workflow without creating a pull request
        required: false
        default: false

      versions:
        type: string
        description: The versions to build the emoji release for
        required: true
        default: ""

  pull_request:
    types:
      - closed
    branches:
      # this will limit the github actions a bit.
      - main
    paths:
      - emojis.lock
      - data/**

permissions: {}

jobs:
  build-emoji-release:
    # only run if the pr was merged and originated from the 'new-emoji-release' branch or manually triggered
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'new-emoji-release') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 10
          persist-credentials: false

      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
        with:
          bun-version: latest

      - name: install dependencies
        run: bun install

      - name: get new releases
        id: new-releases
        if: github.event_name != 'workflow_dispatch'
        run: |
          PREV_COMMIT=$(git rev-parse HEAD^)

          git show $PREV_COMMIT:emojis.lock > previous_emojis.lock

          DIFF=$(jq -n \
            --slurpfile before previous_emojis.lock \
            --slurpfile after emojis.lock \
            '($before[0].versions | map(.emoji_version) | map(tostring)) as $oldVersions |
             ($after[0].versions | map(.emoji_version) | map(tostring)) as $newVersions |
             $newVersions | map(select(. as $v | $oldVersions | index($v) | not))[] |
             select(.)' | tr '\n' ' ')

          echo "DIFF_VERSIONS=$DIFF" >> $GITHUB_OUTPUT

      - name: determine emoji versions
        id: emoji-versions
        env:
          VERSIONS: ${{ github.event.inputs.versions }}
          AUTO_VERSIONS: ${{ steps.new-releases.outputs.DIFF_VERSIONS }}
        run: |
          SEPARATED_VERSIONS=$(echo $VERSIONS | tr ',' ' ')

          # use manual versions if provided, otherwise fallback to auto-detected versions
          FINAL_VERSIONS="${SEPARATED_VERSIONS:-$AUTO_VERSIONS}"

          echo "using versions: $FINAL_VERSIONS"
          echo "FINAL_VERSIONS=$FINAL_VERSIONS" >> $GITHUB_OUTPUT

      - name: generate
        env:
          FINAL_VERSIONS: ${{ steps.emoji-versions.outputs.FINAL_VERSIONS }}
        run: bunx @mojis/cli generate $FINAL_VERSIONS || true

      - name: detect changes for `emojis.lock`
        id: has-lock-changes
        run: |
          # set has-lock-changes to true if emojis.lock has changes
          if git diff --exit-code emojis.lock; then
            echo "no changes detected in emojis.lock"
            echo "has-lock-changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes detected in emojis.lock"
            echo "has-lock-changes=true" >> $GITHUB_OUTPUT
          fi

      - name: create pull request
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7.0.6
        if: ${{ github.event.inputs.dry-run != 'true' && steps.has-lock-changes.outputs.has-lock-changes == 'true' }}
        with:
          commit-message: "feat: update emojis"
          title: "feat: update emojis"
          body: |
            I was recently triggered to update the emoji data, with a new release or multiple releases.

            I don't know what they changed, but I'm sure it's awesome 🤖.

            I will be waiting for your approval 👋.

            This is an automated PR to update the emoji data.
          branch: update-emojis
          add-paths: data/*,emojis.lock
          base: main
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          reviewers: luxass
