name: Detect New Versions

on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: Run the workflow without creating a pull request
        required: false
        default: false

  schedule:
    - cron: "0 0 * * *"

permissions: {}

jobs:
  detect-new-versions:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: 10.5.x

      - name: setup node
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: lts/*

      - name: check latest release
        run: pnpm dlx @mojis/cli@latest emoji-versions all --force --drafts --format json --output emoji-versions.json

      - name: detect changes for `emoji-versions.json`
        id: has-version-changes
        run: |
          # set has-version-changes to true if emoji-versions.json has changes
          if git diff --exit-code emoji-versions.json; then
            echo "no changes detected in emoji-versions.json"
            echo "has-version-changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes detected in emoji-versions.json"
            echo "has-version-changes=true" >> $GITHUB_OUTPUT
          fi

      - name: check for conflicts
        id: check-conflicts
        run: |
          git fetch origin main
          git fetch origin new-emoji-version:new-emoji-version || echo "new-emoji-version branch does not exist"

          if [[ $? -ne 0 ]]; then
            echo "new-emoji-version branch does not exist, no conflicts."
            echo "has-conflicts=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          if git merge-base --is-ancestor new-emoji-version main; then
            echo "No conflicts detected."
            echo "has-conflicts=false" >> $GITHUB_OUTPUT
          else
            echo "Conflicts detected between new-emoji-version and main."
            echo "has-conflicts=true" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: create pull request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        if: ${{ github.event.inputs.dry-run != 'true' && (steps.has-version-changes.outputs.has-version-changes == 'true' || steps.check-conflicts.outputs.has-conflicts == 'true') }}
        with:
          commit-message: "feat: new emoji release"
          title: "feat: new emoji release"
          body: |
            I found a new emoji release 🎉.

            I don't know what they changed, but I'm sure it's awesome 🤖.

            > [!IMPORTANT]
            > When you merge this PR, i will trigger a action to build the new emoji release.

            I will be waiting for your approval 👋.

            This is an automated PR to update the emoji releases.
          branch: new-emoji-version
          add-paths: emoji-versions.json
          base: main
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          reviewers: luxass
