name: stow emoji data

on:
  workflow_dispatch:
  schedule:
    # Run daily at 15:20 UTC
    - cron: "20 15 * * *"

permissions: {}

jobs:
  stow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: discover versions
        id: discover
        run: |
          VERSIONS=$(ls -1 data | tr '\n' ' ')
          echo "discovered versions: $VERSIONS"
          echo "versions=$VERSIONS" >> $GITHUB_OUTPUT

      - name: generate hashes
        id: generate
        env:
          VERSIONS: ${{ steps.discover.outputs.versions }}
        run: |
          VERSIONS_NEEDING_UPDATE=()
          for version in $VERSIONS; do
            echo "processing version: $version"

            # generate hash for current version
            HASH=$(git ls-files ./data/$version | xargs sha256sum | cut -d" " -f1 | sha256sum | cut -d" " -f1)
            echo "hash for $version: $HASH"

            VERSIONS_NEEDING_UPDATE+=($version)

            # generate hashes for first-level files and directories
            ITEMS=$(ls -1 ./data/$version)

            for item in $ITEMS; do
              item_path="./data/$version/$item"

              # generate hash for the item
              if [ -f "$item_path" ]; then
                # it's a file
                ITEM_HASH=$(sha256sum "$item_path" | cut -d" " -f1)
              else
                # it's a directory
                ITEM_HASH=$(git ls-files "$item_path" | xargs sha256sum | cut -d" " -f1 | sha256sum | cut -d" " -f1)
              fi

              echo "hash for $item: $ITEM_HASH"

              VERSIONS_NEEDING_UPDATE+=("$version/$item")
            done
          done

          echo "versions_needing_update=${VERSIONS_NEEDING_UPDATE[@]}" >> $GITHUB_OUTPUT

      - uses: actions/github-script@v7
        env:
          API_KEY: ${{ secrets.MOJI_STOW_API_KEY }}
          VERSIONS_NEEDING_UPDATE: ${{ steps.generate.outputs.versions_needing_update }}
        with:
            script: |
              const { run } = await import('${{ github.workspace }}/.github/scripts/stow.mjs')

              await run()
