name: stow emoji data test

on:
  workflow_dispatch:
    inputs:
      bulk_dirs:
        description: 'Directories to process as a single unit (comma-separated)'
        required: false
        default: "metadata"
        type: string
  schedule:
    - cron: "0 */4 * * *"

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: process emoji data
        env:
          SPECIFIC_BULK_DIRS: ${{ github.event.inputs.bulk_dirs || 'metadata' }}
        run: |
          echo "Hello, world!"
          BULK_DIRS=$(echo "$SPECIFIC_BULK_DIRS" | tr ',' ' ')
          echo "BULK_DIRS: $BULK_DIRS"
